[Convert]
# 规划数据excel表
planning_data = .\Case\ROTS 44\标准算例-JPES-ROTS-44.xlsm
# 报价策略表单
quote_strategy = .\Case\ROTS 44\ROTS现货报价策略表单.xlsx
# 市场配置表单
market_config = .\Case\ROTS 44\ROTS现货市场配置表单.xlsx

# 输入数据中UnitFuel表单的单位价格(元/吨标准煤)字段，是否需要转换为RMB
convert_unit_fuel_price_to_rmb = False

# 输出文件夹_同时也是下一个程序的输入文件夹
output_folder =.\Case\ROTS 44\Input
