[SOLVER]
solver_name = gurobi
cplex_solver = D:\IBM\ILOG\CPLEX_Studio128\cplex\bin\x64_win64\cplex.exe
#mindopt_solver = D:\mindopt\2.1.0\win64-x86\bin\mindoptampl.exe

[CASE]
case_type = 1
case_name = 'ROTS 44' #填入CASE_MAPPING左边key值

[CASE_MAPPING]
山西 = 山西现货
云南 = 云南现货
广东 = 广东现货
IEEE 30 = 30节点现货
HRP-38_西北 = 38节点现货
NREL-118 = 118节点现货
ROTS 44 = ROTS现货

[Convert]
# 采集的对应年
year=2026
# 采集的天, 支持列表和范围，例如[1, 4, 5]和50-89, 以及单个的天,例如10, 从1开始
collect_days = 78-91
# 是否开启并行采集天数据, 建议大于2天时开启
is_parallel = False

# ---算例汇总---
; case_dict={
;     1:'ROTS 44',
;     2:'HRP-38_西北',
;     3:'IEEE 30',
;     4:'NREL-118',
;     5:'广东',
;     6:'山西',
;     7:'云南',
; }