"""Add email column to admin_user

Revision ID: b152495d42aa
Revises: 
Create Date: 2025-12-26 16:12:09.330283
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

revision = 'b152495d42aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_user', sa.Column('email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_user', 'email')
    # ### end Alembic commands ###

